/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  index: [
    {
      type: 'doc',
      id: 'guide/guide',
      label: '目录导航',
    },
    {
      type: 'link',
      label: '☁️ 云原生相关',
      href: '/docs/category/cicd',
    },
    {
      type: 'link',
      label: '😊 Linux基础',
      href: '/docs/category/ansible',
    },
    {
      type: 'link',
      label: '♨️ 编程语言',
      href: '/docs/ProgramLang/Golang/Golang%20Basic',
    },
    {
      type: 'link',
      label: '🕹️ 脚本相关',
      href: '/docs/category/shell-1',
    },
    {
      type: 'link',
      label: '👨‍⚖️ 面试相关',
      href: '/docs/Interview',
    },
  ],
  programLang: [
    {
      type: 'category',
      label: '编程语言',
      link: {type: 'generated-index',},
      items: [
        {
          type: 'category',
          label: 'Golang',
          items: [{
            type: 'autogenerated',
            dirName: 'ProgramLang/Golang',
          }]
        },
        {
          type: 'category',
          label: 'Lua',
          collapsible: true,
          collapsed: true,
          items: [{
            type: 'autogenerated',
            dirName: 'ProgramLang/Lua',
          }]
        },
      ],
    },
  ],
  cloudNative: [
    {
      type: 'category',
      label: '云原生相关',
      link: {type: 'generated-index',},
      items: [{
          type: 'autogenerated',
          dirName: 'CloudNative',
        },
      ],
    },
  ],
  interview: [
    {
      type: 'category',
      label: '面试相关',
      link: {type: 'doc', id: 'Interview/index'},
      items: [{
          type: 'autogenerated',
          dirName: 'Interview/工作面试题',
        },
      ],
    },
  ],
  linuxBasics: [
    {
      type: 'category',
      label: 'Linux基础',
      link: {type: 'generated-index',},
      items: [{
          type: 'autogenerated',
          dirName: 'LinuxBasics',
        },
      ],
    },
  ],
  scripts: [
    {
      type: 'category',
      label: '脚本相关',
      link: {type: 'generated-index',},
      items: [{
          type: 'autogenerated',
          dirName: 'Scripts',
        },
      ],
    },
  ],
};

module.exports = sidebars;
