name: OSS #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - main
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: docusaurus-deploy
      uses: redkubes/docusaurus-deploy-action@v1
      with:
        source-folder: ./
        git-user: AGou-ops
        git-password: ${{ secrets.ACCESS_TOKEN }}
        deployment-branch: gh-pages
    - uses: manyuanrong/setup-ossutil@v2.0
      with:
        # endpoint 可以去oss控制台上查看
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
    - name: Deply To OSS
      run: ossutil cp docs/.vitepress/dist/ oss://agou-ops/myDocsv4 -rf
